import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

// DIRECT TRANSLATIONS - Hardcoded to ensure they work
const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    inventory: "Inventory",
    sales: "Sales",
    purchases: "Purchases",
    transfers: "Transfers",
    reports: "Reports",
    customers: "Customers",
    suppliers: "Suppliers",
    users: "Users",
    roles: "Roles",
    branches: "Branches",
    settings: "Settings",
    profile: "Profile",
    notifications: "Notifications",
    logout: "Logout",
    login: "Login",
    register: "Register",
    
    // Common
    search: "Search...",
    welcome: "Welcome",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    create: "Create",
    update: "Update",
    close: "Close",
    submit: "Submit",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    user: "User",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot Password?",
    changePassword: "Change Password",
    rememberMe: "Remember Me",
    signIn: "Sign In",
    signingIn: "Signing in...",
    
    // Dashboard
    totalRevenue: "Total Revenue",
    totalSales: "Total Sales",
    totalProducts: "Total Products",
    activeUsers: "Active Users",
    alerts: "Alerts",
    recentActivity: "Recent Activity",
    quickActions: "Quick Actions",
    salesTrend: "Sales & Revenue Trend",
    branchPerformance: "Branch Performance",
    inventoryDistribution: "Inventory Distribution",
    monthlyPerformance: "Monthly Performance",
    noActivity: "No recent activity",
    noAlerts: "All systems operating normally",
    lastUpdated: "Last updated",
    thisMonth: "This month",
    onlineNow: "Online now",
    inStock: "In Stock",
    
    // Inventory
    productManagement: "Product Management",
    batchManagement: "Batch Management",
    stockMovements: "Stock Movements",
    productName: "Product Name",
    sku: "SKU",
    category: "Category",
    subCategory: "Sub Category",
    description: "Description",
    unit: "Unit",
    minStock: "Min Stock",
    maxStock: "Max Stock",
    reorderLevel: "Reorder Level",
    quantity: "Quantity",
    remainingQuantity: "Remaining Quantity",
    totalQuantity: "Total Quantity",
    availableQuantity: "Available Quantity",
    batchNumber: "Batch Number",
    batch: "Batch",
    supplier: "Supplier",
    branch: "Branch",
    purchasePrice: "Purchase Price",
    sellingPrice: "Selling Price",
    arrivalDate: "Arrival Date",
    harvestDate: "Harvest Date",
    expiryDate: "Expiry Date",
    grade: "Grade",
    moisturePercentage: "Moisture %",
    freshnessScore: "Freshness Score",
    leafDensity: "Leaf Density",
    stemRatio: "Stem Ratio",
    qualityNotes: "Quality Notes",
    qualityInspection: "Quality Inspection",
    pendingInspection: "Pending Inspection",
    lowStock: "Low Stock",
    expiringSoon: "Expiring Soon",
    available: "Available",
    partial: "Partial",
    expired: "Expired",
    quarantined: "Quarantined",
    disposed: "Disposed",
    createProduct: "Create Product",
    editProduct: "Edit Product",
    createBatch: "Create Batch",
    editBatch: "Edit Batch",
    importCSV: "Import CSV",
    bulkImport: "Bulk Import",
    noProducts: "No products found",
    noBatches: "No batches found",
    addProduct: "Add Product",
    addBatch: "Add Batch",
    completeInspection: "Complete Inspection",
    
    // Sales
    newSale: "New Sale",
    saleNumber: "Sale Number",
    saleDate: "Sale Date",
    customer: "Customer",
    walkInCustomer: "Walk-in Customer",
    items: "Items",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    totalAmount: "Total Amount",
    paidAmount: "Paid Amount",
    balance: "Balance",
    paymentStatus: "Payment Status",
    paymentMethod: "Payment Method",
    payment: "Payment",
    processPayment: "Process Payment",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    returned: "Returned",
    paid: "Paid",
    overdue: "Overdue",
    createSale: "Create Sale",
    saleSummary: "Sale Summary",
    completeSale: "Complete Sale",
    quickAddCustomer: "Quick Add Customer",
    noSales: "No sales found",
    addItem: "Add Item",
    itemPrice: "Unit Price",
    itemTotal: "Item Total",
    
    // Purchases
    newPurchase: "New Purchase",
    purchaseNumber: "Purchase Number",
    purchaseDate: "Purchase Date",
    expectedDelivery: "Expected Delivery",
    actualDelivery: "Actual Delivery",
    orderStatus: "Order Status",
    draft: "Draft",
    ordered: "Ordered",
    received: "Received",
    createPurchase: "Create Purchase Order",
    receiveItems: "Receive Items",
    noPurchases: "No purchases found",
    purchaseItems: "Purchase Items",
    
    // Transfers
    newTransfer: "New Transfer",
    transferNumber: "Transfer Number",
    transferDate: "Transfer Date",
    fromBranch: "From Branch",
    toBranch: "To Branch",
    sourceBranch: "Source Branch",
    destinationBranch: "Destination Branch",
    expectedArrival: "Expected Arrival",
    transferStatus: "Transfer Status",
    approved: "Approved",
    inTransit: "In Transit",
    rejected: "Rejected",
    createTransfer: "Create Transfer",
    noTransfers: "No transfers found",
    itemsToTransfer: "Items to Transfer",
    transferSummary: "Transfer Summary",
    
    // Users
    firstName: "First Name",
    lastName: "Last Name",
    fullName: "Full Name",
    employeeId: "Employee ID",
    role: "Role",
    phone: "Phone Number",
    lastLogin: "Last Login",
    joined: "Joined",
    createUser: "Create User",
    editUser: "Edit User",
    userPermissions: "User Permissions",
    noUsers: "No users found",
    profileInformation: "Profile Information",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    avatar: "Profile Picture",
    resetPassword: "Reset Password"
  },
  am: {
    // Navigation
    dashboard: "ዳሽቦርድ",
    inventory: "ኢንቬንተሪ",
    sales: "ሽያጭ",
    purchases: "ግዢ",
    transfers: "ዝውውር",
    reports: "ሪፖርቶች",
    customers: "ደንበኞች",
    suppliers: "አቅራቢዎች",
    users: "ተጠቃሚዎች",
    roles: "ሚናዎች",
    branches: "ቅርንጫፎች",
    settings: "ቅንብሮች",
    profile: "መገለጫ",
    notifications: "ማሳወቂያዎች",
    logout: "ውጣ",
    login: "ግባ",
    register: "ተመዝገብ",
    
    // Common
    search: "ፈልግ...",
    welcome: "እንኳን ደህና መጡ",
    loading: "በመጫን ላይ...",
    save: "አስቀምጥ",
    cancel: "ሰርዝ",
    delete: "ሰርዝ",
    edit: "አስተካክል",
    add: "ጨምር",
    create: "ፍጠር",
    update: "አዘምን",
    close: "ዝጋ",
    submit: "አስገባ",
    confirm: "አረጋግጥ",
    yes: "አዎ",
    no: "አይ",
    user: "ተጠቃሚ",
    email: "ኢሜይል",
    password: "የይለፍ ቃል",
    forgotPassword: "የይለፍ ቃል ረሱ?",
    changePassword: "የይለፍ ቃል ቀይር",
    rememberMe: "አስታውሰኝ",
    signIn: "ግባ",
    signingIn: "በመግባት ላይ...",
    
    // Dashboard
    totalRevenue: "ጠቅላላ ገቢ",
    totalSales: "ጠቅላላ ሽያጭ",
    totalProducts: "ጠቅላላ ምርቶች",
    activeUsers: "ንቁ ተጠቃሚዎች",
    alerts: "ማንቂያዎች",
    recentActivity: "የቅርብ ጊዜ እንቅስቃሴ",
    quickActions: "ፈጣን ድርጊቶች",
    salesTrend: "የሽያጭ እና ገቢ አዝማሚያ",
    branchPerformance: "የቅርንጫፍ አፈጻጸም",
    inventoryDistribution: "የእቃ ክምችት ስርጭት",
    monthlyPerformance: "ወርሃዊ አፈጻጸም",
    noActivity: "ምንም የቅርብ ጊዜ እንቅስቃሴ የለም",
    noAlerts: "ሁሉም ስርዓቶች በመደበኛነት እየሰሩ ናቸው",
    lastUpdated: "የመጨረሻ ማዘመን",
    thisMonth: "በዚህ ወር",
    onlineNow: "አሁን በመስመር ላይ",
    inStock: "በክምችት ውስጥ",
    
    // Inventory
    productManagement: "የምርት አስተዳደር",
    batchManagement: "የባች አስተዳደር",
    stockMovements: "የእቃ እንቅስቃሴ",
    productName: "የምርት ስም",
    sku: "SKU",
    category: "ምድብ",
    subCategory: "ንዑስ ምድብ",
    description: "መግለጫ",
    unit: "አሃድ",
    minStock: "ዝቅተኛ ክምችት",
    maxStock: "ከፍተኛ ክምችት",
    reorderLevel: "የድጋሚ ትዕዛዝ ደረጃ",
    quantity: "ብዛት",
    remainingQuantity: "የቀረ ብዛት",
    totalQuantity: "ጠቅላላ ብዛት",
    availableQuantity: "ያለ ብዛት",
    batchNumber: "የባች ቁጥር",
    batch: "ባች",
    supplier: "አቅራቢ",
    branch: "ቅርንጫፍ",
    purchasePrice: "የግዢ ዋጋ",
    sellingPrice: "የሽያጭ ዋጋ",
    arrivalDate: "የመድረሻ ቀን",
    harvestDate: "የመሰብሰቢያ ቀን",
    expiryDate: "የማብቂያ ቀን",
    grade: "ደረጃ",
    moisturePercentage: "የእርጥበት መቶኛ",
    freshnessScore: "የትኩስነት ውጤት",
    leafDensity: "የቅጠል ጥግግት",
    stemRatio: "የግንድ ጥምርታ",
    qualityNotes: "የጥራት ማስታወሻዎች",
    qualityInspection: "የጥራት ምርመራ",
    pendingInspection: "ምርመራ በመጠባበቅ ላይ",
    lowStock: "ዝቅተኛ ክምችት",
    expiringSoon: "በቅርቡ የሚያበቃ",
    available: "ይገኛል",
    partial: "ከፊል",
    expired: "አልቋል",
    quarantined: "በኳራንቲን ውስጥ",
    disposed: "ተወግዷል",
    createProduct: "ምርት ፍጠር",
    editProduct: "ምርት አስተካክል",
    createBatch: "ባች ፍጠር",
    editBatch: "ባች አስተካክል",
    importCSV: "CSV አስገባ",
    bulkImport: "በብዛት አስገባ",
    noProducts: "ምንም ምርቶች አልተገኙም",
    noBatches: "ምንም ባችዎች አልተገኙም",
    addProduct: "ምርት ጨምር",
    addBatch: "ባች ጨምር",
    completeInspection: "ምርመራ አጠናቅቅ",
    
    // Sales
    newSale: "አዲስ ሽያጭ",
    saleNumber: "የሽያጭ ቁጥር",
    saleDate: "የሽያጭ ቀን",
    customer: "ደንበኛ",
    walkInCustomer: "የጎበኘ ደንበኛ",
    items: "እቃዎች",
    subtotal: "ንዑስ ድምር",
    tax: "ግብር",
    discount: "ቅናሽ",
    totalAmount: "ጠቅላላ ድምር",
    paidAmount: "የተከፈለ ድምር",
    balance: "ቀሪ",
    paymentStatus: "የክፍያ ሁኔታ",
    paymentMethod: "የክፍያ ዘዴ",
    payment: "ክፍያ",
    processPayment: "ክፍያ አከናውን",
    pending: "በመጠባበቅ ላይ",
    completed: "ተጠናቋል",
    cancelled: "ተሰርዟል",
    returned: "ተመልሷል",
    paid: "ተከፍሏል",
    overdue: "ዘግይቷል",
    createSale: "ሽያጭ ፍጠር",
    saleSummary: "የሽያጭ ማጠቃለያ",
    completeSale: "ሽያጭ አጠናቅቅ",
    quickAddCustomer: "ደንበኛ በፍጥነት ጨምር",
    noSales: "ምንም ሽያጮች አልተገኙም",
    addItem: "እቃ ጨምር",
    itemPrice: "የእቃ ዋጋ",
    itemTotal: "የእቃ ድምር",
    
    // Purchases
    newPurchase: "አዲስ ግዢ",
    purchaseNumber: "የግዢ ቁጥር",
    purchaseDate: "የግዢ ቀን",
    expectedDelivery: "የሚጠበቀው መላኪያ",
    actualDelivery: "ትክክለኛው መላኪያ",
    orderStatus: "የትዕዛዝ ሁኔታ",
    draft: "ረቂቅ",
    ordered: "ታዘዟል",
    received: "ተቀብሏል",
    createPurchase: "የግዢ ትዕዛዝ ፍጠር",
    receiveItems: "እቃዎች ተቀበል",
    noPurchases: "ምንም ግዢዎች አልተገኙም",
    purchaseItems: "የግዢ እቃዎች",
    
    // Transfers
    newTransfer: "አዲስ ዝውውር",
    transferNumber: "የዝውውር ቁጥር",
    transferDate: "የዝውውር ቀን",
    fromBranch: "ከሚመጣበት ቅርንጫፍ",
    toBranch: "ወደሚሄድበት ቅርንጫፍ",
    sourceBranch: "ምንጭ ቅርንጫፍ",
    destinationBranch: "መድረሻ ቅርንጫፍ",
    expectedArrival: "የሚጠበቀው መድረሻ",
    transferStatus: "የዝውውር ሁኔታ",
    approved: "ተፈቅዷል",
    inTransit: "በመጓዝ ላይ",
    rejected: "ተቀባይነት አላገኘም",
    createTransfer: "ዝውውር ፍጠር",
    noTransfers: "ምንም ዝውውሮች አልተገኙም",
    itemsToTransfer: "ለማዛወር የሚቻሉ እቃዎች",
    transferSummary: "የዝውውር ማጠቃለያ",
    
    // Users
    firstName: "ስም",
    lastName: "የአባት ስም",
    fullName: "ሙሉ ስም",
    employeeId: "የሰራተኛ መለያ",
    role: "ሚና",
    phone: "ስልክ ቁጥር",
    lastLogin: "የመጨረሻ መግቢያ",
    joined: "የተመዘገበበት",
    createUser: "ተጠቃሚ ፍጠር",
    editUser: "ተጠቃሚ አስተካክል",
    userPermissions: "የተጠቃሚ ፍቃዶች",
    noUsers: "ምንም ተጠቃሚዎች አልተገኙም",
    profileInformation: "የመገለጫ መረጃ",
    editProfile: "መገለጫ አስተካክል",
    saveChanges: "ለውጦች አስቀምጥ",
    avatar: "የመገለጫ ምስል",
    resetPassword: "የይለፍ ቃል ዳግም አስጀምር"
  }
};

export const LanguageProvider = ({ children }) => {
  const getInitialLanguage = () => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  };

  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    if (!translations[language]) {
      return translations.en[key] || key;
    }
    const result = translations[language][key];
    if (!result) {
      return translations.en[key] || key;
    }
    return result;
  };

  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'am' : 'en';
    setLanguage(newLang);
    localStorage.setItem('language', newLang);
    window.location.reload();
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
