import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    // ==================== COMMON ====================
    appName: "Khat Inventory",
    search: "Search...",
    welcome: "Welcome",
    profile: "My Profile",
    changePassword: "Change Password",
    notifications: "Notifications",
    logout: "Logout",
    user: "User",
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    create: "Create",
    update: "Update",
    close: "Close",
    submit: "Submit",
    confirm: "Confirm",
    yes: "Yes",
    no: "No",
    print: "Print",
    export: "Export",
    refresh: "Refresh",
    clear: "Clear",
    upload: "Upload",
    all: "All",
    none: "None",
    or: "or",
    notes: "Notes",
    contact: "Contact",
    warning: "Warning",
    success: "Success",
    status: "Status",
    amount: "Amount",
    total: "Total",
    actions: "Actions",
    created: "Created",
    updated: "Updated",
    items: "Items",
    of: "of",
    page: "Page",
    previous: "Previous",
    next: "Next",
    clickToUpload: "Click to upload",
    files: "files",
    used: "Used",
    resource: "Resource",
    active: "Active",
    inactive: "Inactive",
    view: "View",

    // ==================== NAVIGATION ====================
    dashboard: "Dashboard",
    inventory: "Inventory",
    products: "Products",
    batches: "Batches",
    stockMovements: "Stock Movements",
    sales: "Sales",
    purchases: "Purchases",
    transfers: "Transfers",
    reports: "Reports",
    customers: "Customers",
    suppliers: "Suppliers",
    users: "Users",
    roles: "Roles & Permissions",
    branches: "Branches",
    settings: "Settings",
    auditLogs: "Audit Logs",

    navigation: {
      main: "Main",
      operations: "Operations",
      management: "Management",
      system: "System"
    },

    // ==================== AUTH ====================
    login: "Login",
    loginTitle: "Sign in to your account",
    register: "Register",
    email: "Email Address",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    rememberMe: "Remember Me",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalidCredentials: "Invalid email or password",
    sessionExpired: "Session expired. Please login again",
    passwordChanged: "Password changed successfully",
    passwordReset: "Password reset email sent",
    currentPassword: "Current Password",
    newPassword: "New Password",
    minPassword: "Password must be at least 8 characters",
    passwordMismatch: "Passwords do not match",
    loginSuccess: "Login successful",
    logoutSuccess: "Logged out successfully",
    welcomeBack: "Welcome back",
    defaultAdmin: "Default admin: admin@khattrading.com / Admin@123",

    // ==================== DASHBOARD ====================
    totalRevenue: "Total Revenue",
    totalSales: "Total Sales",
    totalProducts: "Total Products",
    activeUsers: "Active Users",
    alerts: "Alerts",
    recentActivity: "Recent Activity",
    quickActions: "Quick Actions",
    salesTrend: "Sales & Revenue Trend",
    branchPerformance: "Branch Performance",
    inventoryDistribution: "Inventory Distribution",
    monthlyPerformance: "Monthly Performance",
    noActivity: "No recent activity",
    noAlerts: "All systems operating normally",
    lastUpdated: "Last updated",
    thisMonth: "This month",
    onlineNow: "Online now",
    inStock: "In Stock",
    executive: "Executive Dashboard",
    overview: "Overview of company performance",
    refresh: "Refresh",

    // ==================== INVENTORY / PRODUCTS ====================
    title: "Inventory Management",
    productManagement: "Product Management",
    batchManagement: "Batch Management",
    productName: "Product Name",
    sku: "SKU",
    category: "Category",
    subCategory: "Sub Category",
    description: "Description",
    unit: "Unit",
    minStock: "Min Stock",
    maxStock: "Max Stock",
    reorderLevel: "Reorder Level",
    quantity: "Quantity",
    remainingQuantity: "Remaining Quantity",
    totalQuantity: "Total Quantity",
    availableQuantity: "Available Quantity",
    batchNumber: "Batch Number",
    batch: "Batch",
    supplier: "Supplier",
    branch: "Branch",
    purchasePrice: "Purchase Price",
    sellingPrice: "Selling Price",
    arrivalDate: "Arrival Date",
    harvestDate: "Harvest Date",
    expiryDate: "Expiry Date",
    grade: "Grade",
    moisturePercentage: "Moisture %",
    freshnessScore: "Freshness Score",
    leafDensity: "Leaf Density",
    stemRatio: "Stem Ratio",
    qualityNotes: "Quality Notes",
    qualityInspection: "Quality Inspection",
    pendingInspection: "Pending Inspection",
    lowStock: "Low Stock",
    expiringSoon: "Expiring Soon",
    available: "Available",
    partial: "Partial",
    expired: "Expired",
    quarantined: "Quarantined",
    disposed: "Disposed",
    createProduct: "Create Product",
    editProduct: "Edit Product",
    createBatch: "Create Batch",
    editBatch: "Edit Batch",
    importCSV: "Import CSV",
    bulkImport: "Bulk Import",
    noProducts: "No products found",
    noBatches: "No batches found",
    addProduct: "Add Product",
    addBatch: "Add Batch",
    completeInspection: "Complete Inspection",
    addItem: "Add Item",
    itemPrice: "Unit Price",
    itemTotal: "Item Total",

    // ==================== SALES ====================
    newSale: "New Sale",
    saleNumber: "Sale Number",
    saleDate: "Sale Date",
    customer: "Customer",
    walkInCustomer: "Walk-in Customer",
    items: "Items",
    subtotal: "Subtotal",
    tax: "Tax",
    discount: "Discount",
    totalAmount: "Total Amount",
    paidAmount: "Paid Amount",
    balance: "Balance",
    paymentStatus: "Payment Status",
    paymentMethod: "Payment Method",
    payment: "Payment",
    processPayment: "Process Payment",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    returned: "Returned",
    paid: "Paid",
    overdue: "Overdue",
    createSale: "Create Sale",
    saleSummary: "Sale Summary",
    completeSale: "Complete Sale",
    quickAddCustomer: "Quick Add Customer",
    noSales: "No sales found",
    view: "View",

    // ==================== PURCHASES ====================
    newPurchase: "New Purchase",
    purchaseNumber: "Purchase Number",
    purchaseDate: "Purchase Date",
    expectedDelivery: "Expected Delivery",
    actualDelivery: "Actual Delivery",
    orderStatus: "Order Status",
    draft: "Draft",
    ordered: "Ordered",
    received: "Received",
    createPurchase: "Create Purchase Order",
    receiveItems: "Receive Items",
    noPurchases: "No purchases found",
    purchaseItems: "Purchase Items",

    // ==================== TRANSFERS ====================
    newTransfer: "New Transfer",
    transferNumber: "Transfer Number",
    transferDate: "Transfer Date",
    fromBranch: "From Branch",
    toBranch: "To Branch",
    sourceBranch: "Source Branch",
    destinationBranch: "Destination Branch",
    expectedArrival: "Expected Arrival",
    transferStatus: "Transfer Status",
    approved: "Approved",
    inTransit: "In Transit",
    rejected: "Rejected",
    createTransfer: "Create Transfer",
    noTransfers: "No transfers found",
    itemsToTransfer: "Items to Transfer",
    transferSummary: "Transfer Summary",

    // ==================== USERS ====================
    firstName: "First Name",
    lastName: "Last Name",
    fullName: "Full Name",
    employeeId: "Employee ID",
    role: "Role",
    phone: "Phone Number",
    lastLogin: "Last Login",
    joined: "Joined",
    createUser: "Create User",
    editUser: "Edit User",
    userPermissions: "User Permissions",
    noUsers: "No users found",
    profileInformation: "Profile Information",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    avatar: "Profile Picture",
    resetPassword: "Reset Password",

    // ==================== BRANCHES ====================
    branchName: "Branch Name",
    branchCode: "Branch Code",
    branchType: "Branch Type",
    headquarters: "Headquarters",
    warehouse: "Warehouse",
    createBranch: "Create Branch",
    editBranch: "Edit Branch",
    noBranches: "No branches found",
    addBranch: "Add Branch",
    address: "Address",

    // ==================== SUPPLIERS ====================
    supplierName: "Supplier Name",
    supplierCode: "Supplier Code",
    contactPerson: "Contact Person",
    createSupplier: "Create Supplier",
    editSupplier: "Edit Supplier",
    noSuppliers: "No suppliers found",

    // ==================== CUSTOMERS ====================
    customerName: "Customer Name",
    customerCode: "Customer Code",
    customerType: "Customer Type",
    individual: "Individual",
    business: "Business",
    wholesale: "Wholesale",
    retail: "Retail",
    creditLimit: "Credit Limit",
    paymentTerms: "Payment Terms",
    taxId: "Tax ID",
    createCustomer: "Create Customer",
    editCustomer: "Edit Customer",
    noCustomers: "No customers found",
    creditHistory: "Credit History",
    totalCredit: "Total Credit Given",
    totalPayments: "Total Payments",
    currentBalance: "Current Balance",

    // ==================== REPORTS ====================
    inventoryReport: "Inventory Report",
    salesReport: "Sales Report",
    profitReport: "Profit Report",
    dateRange: "Date Range",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    lastMonth: "Last Month",
    thisQuarter: "This Quarter",
    thisYear: "This Year",
    customRange: "Custom Range",
    startDate: "Start Date",
    endDate: "End Date",
    total: "Total",
    revenue: "Revenue",
    cost: "Cost",
    profit: "Profit",
    margin: "Margin",
    averageOrderValue: "Average Order Value",
    topProduct: "Top Product",
    exportPDF: "Export PDF",
    exportExcel: "Export Excel",
    applyFilters: "Apply Filters",
    clearFilters: "Clear Filters",
    noData: "No data available for the selected period",

    // ==================== NOTIFICATIONS ====================
    notificationCenter: "Notification Center",
    unread: "unread",
    read: "Read",
    markAllRead: "Mark All Read",
    deleteAll: "Delete All",
    noNotifications: "No notifications",
    allCaughtUp: "You're all caught up!",
    markAsRead: "Mark as read",
    newNotification: "New",
    viewAll: "View All Notifications",

    // ==================== SETTINGS ====================
    general: "General Settings",
    security: "Security",
    companyName: "Company Name",
    companyEmail: "Company Email",
    companyPhone: "Company Phone",
    companyAddress: "Company Address",
    currency: "Currency",
    timezone: "Timezone",
    dateFormat: "Date Format",
    saveSettings: "Save Settings",
    settingsSaved: "Settings saved successfully",
    sessionTimeout: "Session Timeout (minutes)",
    maxLoginAttempts: "Max Login Attempts",
    preferences: "Preferences",

    // ==================== MODALS ====================
    confirmDelete: "Confirm Delete",
    areYouSure: "Are you sure?",
    deleteWarning: "This action cannot be undone.",

    // ==================== ERRORS ====================
    error: "Something went wrong",
    notFound: "Page not found",
    unauthorized: "Unauthorized access",
    forbidden: "Access denied",
    serverError: "Server error",
    networkError: "Network error",
    tryAgain: "Please try again",
    retry: "Retry",

    // ==================== POS ====================
    cart: "Cart",
    addToCart: "Add to Cart",
    removeFromCart: "Remove from Cart",
    clearCart: "Clear Cart",
    cartEmpty: "Cart is empty",
    checkout: "Checkout",
    cash: "Cash",
    card: "Card",
    mobileMoney: "Mobile Money",
    change: "Change",
    receipt: "Receipt",
    printReceipt: "Print Receipt",
    paymentSuccess: "Payment successful",
    paymentFailed: "Payment failed",
    scanProduct: "Scan or search product",
    price: "Price"
  },

  am: {
    // ==================== COMMON ====================
    appName: "ካት ኢንቬንተሪ",
    search: "ፈልግ...",
    welcome: "እንኳን ደህና መጡ",
    profile: "መገለጫ",
    changePassword: "የይለፍ ቃል ቀይር",
    notifications: "ማሳወቂያዎች",
    logout: "ውጣ",
    user: "ተጠቃሚ",
    loading: "በመጫን ላይ...",
    save: "አስቀምጥ",
    cancel: "ሰርዝ",
    delete: "ሰርዝ",
    edit: "አስተካክል",
    add: "ጨምር",
    create: "ፍጠር",
    update: "አዘምን",
    close: "ዝጋ",
    submit: "አስገባ",
    confirm: "አረጋግጥ",
    yes: "አዎ",
    no: "አይ",
    print: "አትም",
    export: "ላክ",
    refresh: "አድስ",
    clear: "አጽዳ",
    upload: "ጫን",
    all: "ሁሉም",
    none: "ምንም",
    or: "ወይም",
    notes: "ማስታወሻዎች",
    contact: "የመገናኛ",
    warning: "ማንቂያ",
    success: "ተሳካ",
    status: "ሁኔታ",
    amount: "መጠን",
    total: "ድምር",
    actions: "ድርጊቶች",
    created: "ተፈጠረ",
    updated: "ተዘመነ",
    items: "እቃዎች",
    of: "ከ",
    page: "ገጽ",
    previous: "ቀዳሚ",
    next: "ቀጣይ",
    clickToUpload: "ለመጫን ይጫኑ",
    files: "ፋይሎች",
    used: "ጥቅም ላይ የዋለ",
    resource: "ምንጭ",
    active: "ንቁ",
    inactive: "የቆመ",
    view: "ይመልከቱ",

    // ==================== NAVIGATION ====================
    dashboard: "ዳሽቦርድ",
    inventory: "ኢንቬንተሪ",
    products: "ምርቶች",
    batches: "ባችዎች",
    stockMovements: "የእቃ እንቅስቃሴ",
    sales: "ሽያጭ",
    purchases: "ግዢ",
    transfers: "ዝውውር",
    reports: "ሪፖርቶች",
    customers: "ደንበኞች",
    suppliers: "አቅራቢዎች",
    users: "ተጠቃሚዎች",
    roles: "ሚናዎች እና ፍቃዶች",
    branches: "ቅርንጫፎች",
    settings: "ቅንብሮች",
    auditLogs: "የኦዲት መዝገቦች",

    navigation: {
      main: "ዋና",
      operations: "ሥራዎች",
      management: "አስተዳደር",
      system: "ሲስተም"
    },

    // ==================== AUTH ====================
    login: "ግባ",
    loginTitle: "ወደ መለያዎ ይግቡ",
    register: "ተመዝገብ",
    email: "ኢሜይል አድራሻ",
    password: "የይለፍ ቃል",
    confirmPassword: "የይለፍ ቃል አረጋግጥ",
    forgotPassword: "የይለፍ ቃል ረሱ?",
    rememberMe: "አስታውሰኝ",
    signIn: "ግባ",
    signingIn: "በመግባት ላይ...",
    invalidCredentials: "የተሳሳተ ኢሜይል ወይም የይለፍ ቃል",
    sessionExpired: "ክፍለ ጊዜ አልቋል። እባክዎ እንደገና ይግቡ",
    passwordChanged: "የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል",
    passwordReset: "የይለፍ ቃል ዳግም ማስጀመሪያ ኢሜይል ተልኳል",
    currentPassword: "አሁን ያለው የይለፍ ቃል",
    newPassword: "አዲስ የይለፍ ቃል",
    minPassword: "የይለፍ ቃል ቢያንስ 8 ቁምፊዎች መሆን አለበት",
    passwordMismatch: "የይለፍ ቃሎች አይዛመዱም",
    loginSuccess: "በተሳካ ሁኔታ ገብተዋል",
    logoutSuccess: "በተሳካ ሁኔታ ወጥተዋል",
    welcomeBack: "እንኳን በደህና መጡ",
    defaultAdmin: "ነባሪ አስተዳዳሪ: admin@khattrading.com / Admin@123",

    // ==================== DASHBOARD ====================
    totalRevenue: "ጠቅላላ ገቢ",
    totalSales: "ጠቅላላ ሽያጭ",
    totalProducts: "ጠቅላላ ምርቶች",
    activeUsers: "ንቁ ተጠቃሚዎች",
    alerts: "ማንቂያዎች",
    recentActivity: "የቅርብ ጊዜ እንቅስቃሴ",
    quickActions: "ፈጣን ድርጊቶች",
    salesTrend: "የሽያጭ እና ገቢ አዝማሚያ",
    branchPerformance: "የቅርንጫፍ አፈጻጸም",
    inventoryDistribution: "የእቃ ክምችት ስርጭት",
    monthlyPerformance: "ወርሃዊ አፈጻጸም",
    noActivity: "ምንም የቅርብ ጊዜ እንቅስቃሴ የለም",
    noAlerts: "ሁሉም ስርዓቶች በመደበኛነት እየሰሩ ናቸው",
    lastUpdated: "የመጨረሻ ማዘመን",
    thisMonth: "በዚህ ወር",
    onlineNow: "አሁን በመስመር ላይ",
    inStock: "በክምችት ውስጥ",
    executive: "የሥራ አስፈፃሚ ዳሽቦርድ",
    overview: "የኩባንያው አፈፃፀም አጠቃላይ እይታ",
    refresh: "አድስ",

    // ==================== INVENTORY / PRODUCTS ====================
    title: "የኢንቬንተሪ አስተዳደር",
    productManagement: "የምርት አስተዳደር",
    batchManagement: "የባች አስተዳደር",
    productName: "የምርት ስም",
    sku: "SKU",
    category: "ምድብ",
    subCategory: "ንዑስ ምድብ",
    description: "መግለጫ",
    unit: "አሃድ",
    minStock: "ዝቅተኛ ክምችት",
    maxStock: "ከፍተኛ ክምችት",
    reorderLevel: "የድጋሚ ትዕዛዝ ደረጃ",
    quantity: "ብዛት",
    remainingQuantity: "የቀረ ብዛት",
    totalQuantity: "ጠቅላላ ብዛት",
    availableQuantity: "ያለ ብዛት",
    batchNumber: "የባች ቁጥር",
    batch: "ባች",
    supplier: "አቅራቢ",
    branch: "ቅርንጫፍ",
    purchasePrice: "የግዢ ዋጋ",
    sellingPrice: "የሽያጭ ዋጋ",
    arrivalDate: "የመድረሻ ቀን",
    harvestDate: "የመሰብሰቢያ ቀን",
    expiryDate: "የማብቂያ ቀን",
    grade: "ደረጃ",
    moisturePercentage: "የእርጥበት መቶኛ",
    freshnessScore: "የትኩስነት ውጤት",
    leafDensity: "የቅጠል ጥግግት",
    stemRatio: "የግንድ ጥምርታ",
    qualityNotes: "የጥራት ማስታወሻዎች",
    qualityInspection: "የጥራት ምርመራ",
    pendingInspection: "ምርመራ በመጠባበቅ ላይ",
    lowStock: "ዝቅተኛ ክምችት",
    expiringSoon: "በቅርቡ የሚያበቃ",
    available: "ይገኛል",
    partial: "ከፊል",
    expired: "አልቋል",
    quarantined: "በኳራንቲን ውስጥ",
    disposed: "ተወግዷል",
    createProduct: "ምርት ፍጠር",
    editProduct: "ምርት አስተካክል",
    createBatch: "ባች ፍጠር",
    editBatch: "ባች አስተካክል",
    importCSV: "CSV አስገባ",
    bulkImport: "በብዛት አስገባ",
    noProducts: "ምንም ምርቶች አልተገኙም",
    noBatches: "ምንም ባችዎች አልተገኙም",
    addProduct: "ምርት ጨምር",
    addBatch: "ባች ጨምር",
    completeInspection: "ምርመራ አጠናቅቅ",
    addItem: "እቃ ጨምር",
    itemPrice: "የእቃ ዋጋ",
    itemTotal: "የእቃ ድምር",

    // ==================== SALES ====================
    newSale: "አዲስ ሽያጭ",
    saleNumber: "የሽያጭ ቁጥር",
    saleDate: "የሽያጭ ቀን",
    customer: "ደንበኛ",
    walkInCustomer: "የጎበኘ ደንበኛ",
    items: "እቃዎች",
    subtotal: "ንዑስ ድምር",
    tax: "ግብር",
    discount: "ቅናሽ",
    totalAmount: "ጠቅላላ ድምር",
    paidAmount: "የተከፈለ ድምር",
    balance: "ቀሪ",
    paymentStatus: "የክፍያ ሁኔታ",
    paymentMethod: "የክፍያ ዘዴ",
    payment: "ክፍያ",
    processPayment: "ክፍያ አከናውን",
    pending: "በመጠባበቅ ላይ",
    completed: "ተጠናቋል",
    cancelled: "ተሰርዟል",
    returned: "ተመልሷል",
    paid: "ተከፍሏል",
    overdue: "ዘግይቷል",
    createSale: "ሽያጭ ፍጠር",
    saleSummary: "የሽያጭ ማጠቃለያ",
    completeSale: "ሽያጭ አጠናቅቅ",
    quickAddCustomer: "ደንበኛ በፍጥነት ጨምር",
    noSales: "ምንም ሽያጮች አልተገኙም",
    view: "ይመልከቱ",

    // ==================== PURCHASES ====================
    newPurchase: "አዲስ ግዢ",
    purchaseNumber: "የግዢ ቁጥር",
    purchaseDate: "የግዢ ቀን",
    expectedDelivery: "የሚጠበቀው መላኪያ",
    actualDelivery: "ትክክለኛው መላኪያ",
    orderStatus: "የትዕዛዝ ሁኔታ",
    draft: "ረቂቅ",
    ordered: "ታዘዟል",
    received: "ተቀብሏል",
    createPurchase: "የግዢ ትዕዛዝ ፍጠር",
    receiveItems: "እቃዎች ተቀበል",
    noPurchases: "ምንም ግዢዎች አልተገኙም",
    purchaseItems: "የግዢ እቃዎች",

    // ==================== TRANSFERS ====================
    newTransfer: "አዲስ ዝውውር",
    transferNumber: "የዝውውር ቁጥር",
    transferDate: "የዝውውር ቀን",
    fromBranch: "ከሚመጣበት ቅርንጫፍ",
    toBranch: "ወደሚሄድበት ቅርንጫፍ",
    sourceBranch: "ምንጭ ቅርንጫፍ",
    destinationBranch: "መድረሻ ቅርንጫፍ",
    expectedArrival: "የሚጠበቀው መድረሻ",
    transferStatus: "የዝውውር ሁኔታ",
    approved: "ተፈቅዷል",
    inTransit: "በመጓዝ ላይ",
    rejected: "ተቀባይነት አላገኘም",
    createTransfer: "ዝውውር ፍጠር",
    noTransfers: "ምንም ዝውውሮች አልተገኙም",
    itemsToTransfer: "ለማዛወር የሚቻሉ እቃዎች",
    transferSummary: "የዝውውር ማጠቃለያ",

    // ==================== USERS ====================
    firstName: "ስም",
    lastName: "የአባት ስም",
    fullName: "ሙሉ ስም",
    employeeId: "የሰራተኛ መለያ",
    role: "ሚና",
    phone: "ስልክ ቁጥር",
    lastLogin: "የመጨረሻ መግቢያ",
    joined: "የተመዘገበበት",
    createUser: "ተጠቃሚ ፍጠር",
    editUser: "ተጠቃሚ አስተካክል",
    userPermissions: "የተጠቃሚ ፍቃዶች",
    noUsers: "ምንም ተጠቃሚዎች አልተገኙም",
    profileInformation: "የመገለጫ መረጃ",
    editProfile: "መገለጫ አስተካክል",
    saveChanges: "ለውጦች አስቀምጥ",
    avatar: "የመገለጫ ምስል",
    resetPassword: "የይለፍ ቃል ዳግም አስጀምር",

    // ==================== BRANCHES ====================
    branchName: "የቅርንጫፍ ስም",
    branchCode: "የቅርንጫፍ ኮድ",
    branchType: "የቅርንጫፍ አይነት",
    headquarters: "ዋና መሥሪያ ቤት",
    warehouse: "መጋዘን",
    createBranch: "ቅርንጫፍ ፍጠር",
    editBranch: "ቅርንጫፍ አስተካክል",
    noBranches: "ምንም ቅርንጫፎች አልተገኙም",
    addBranch: "ቅርንጫፍ ጨምር",
    address: "አድራሻ",

    // ==================== SUPPLIERS ====================
    supplierName: "የአቅራቢ ስም",
    supplierCode: "የአቅራቢ ኮድ",
    contactPerson: "የሚገናኝ ሰው",
    createSupplier: "አቅራቢ ፍጠር",
    editSupplier: "አቅራቢ አስተካክል",
    noSuppliers: "ምንም አቅራቢዎች አልተገኙም",

    // ==================== CUSTOMERS ====================
    customerName: "የደንበኛ ስም",
    customerCode: "የደንበኛ ኮድ",
    customerType: "የደንበኛ አይነት",
    individual: "ግለሰብ",
    business: "ንግድ",
    wholesale: "በጅምላ",
    retail: "በችርቻሮ",
    creditLimit: "የብድር ገደብ",
    paymentTerms: "የክፍያ ውሎች",
    taxId: "የግብር መለያ",
    createCustomer: "ደንበኛ ፍጠር",
    editCustomer: "ደንበኛ አስተካክል",
    noCustomers: "ምንም ደንበኞች አልተገኙም",
    creditHistory: "የብድር ታሪክ",
    totalCredit: "ጠቅላላ የተሰጠ ብድር",
    totalPayments: "ጠቅላላ ክፍያዎች",
    currentBalance: "አሁን ያለው ቀሪ",

    // ==================== REPORTS ====================
    inventoryReport: "የኢንቬንተሪ ሪፖርት",
    salesReport: "የሽያጭ ሪፖርት",
    profitReport: "የትርፍ ሪፖርት",
    dateRange: "የቀን ክልል",
    today: "ዛሬ",
    yesterday: "ትናንት",
    thisWeek: "በዚህ ሳምንት",
    lastWeek: "ባለፈው ሳምንት",
    lastMonth: "ባለፈው ወር",
    thisQuarter: "በዚህ ሩብ",
    thisYear: "በዚህ ዓመት",
    customRange: "ብጁ ክልል",
    startDate: "የመጀመሪያ ቀን",
    endDate: "የመጨረሻ ቀን",
    total: "ድምር",
    revenue: "ገቢ",
    cost: "ወጪ",
    profit: "ትርፍ",
    margin: "ህዳግ",
    averageOrderValue: "አማካይ የትዕዛዝ ዋጋ",
    topProduct: "ከፍተኛ ምርት",
    exportPDF: "PDF ላክ",
    exportExcel: "Excel ላክ",
    applyFilters: "ማጣሪያዎችን ተግብር",
    clearFilters: "ማጣሪያዎችን አጽዳ",
    noData: "ለተመረጠው ጊዜ ምንም መረጃ የለም",

    // ==================== NOTIFICATIONS ====================
    notificationCenter: "የማሳወቂያ ማዕከል",
    unread: "ያልተነበበ",
    read: "ተነብቧል",
    markAllRead: "ሁሉም እንደተነበበ ምልክት አድርግ",
    deleteAll: "ሁሉም ሰርዝ",
    noNotifications: "ምንም ማሳወቂያዎች የሉም",
    allCaughtUp: "ሁሉንም አይተዋል!",
    markAsRead: "እንደተነበበ ምልክት አድርግ",
    newNotification: "አዲስ",
    viewAll: "ሁሉንም ማሳወቂያዎች ይመልከቱ",

    // ==================== SETTINGS ====================
    general: "አጠቃላይ ቅንብሮች",
    security: "ደህንነት",
    companyName: "የኩባንያ ስም",
    companyEmail: "የኩባንያ ኢሜይል",
    companyPhone: "የኩባንያ ስልክ",
    companyAddress: "የኩባንያ አድራሻ",
    currency: "ገንዘብ",
    timezone: "የሰዓት ሰቅ",
    dateFormat: "የቀን ቅርጸት",
    saveSettings: "ቅንብሮችን አስቀምጥ",
    settingsSaved: "ቅንብሮች በተሳካ ሁኔታ ተቀምጠዋል",
    sessionTimeout: "የክፍለ ጊዜ ጊዜ ማብቂያ (ደቂቃዎች)",
    maxLoginAttempts: "ከፍተኛ የመግቢያ ሙከራዎች",
    preferences: "ምርጫዎች",

    // ==================== MODALS ====================
    confirmDelete: "መሰረዝ አረጋግጥ",
    areYouSure: "እርግጠኛ ነዎት?",
    deleteWarning: "ይህ ድርጊት ሊቀለበስ አይችልም።",

    // ==================== ERRORS ====================
    error: "ስህተት ተከስቷል",
    notFound: "ገጽ አልተገኘም",
    unauthorized: "ያልተፈቀደ መዳረሻ",
    forbidden: "መዳረሻ ተከልክሏል",
    serverError: "የአገልጋይ ስህተት",
    networkError: "የአውታረ መረብ ስህተት",
    tryAgain: "እባክዎ እንደገና ይሞክሩ",
    retry: "ደግመህ ሞክር",

    // ==================== POS ====================
    cart: "የግዢ ቅርጫት",
    addToCart: "ወደ ግዢ ቅርጫት ጨምር",
    removeFromCart: "ከግዢ ቅርጫት አስወግድ",
    clearCart: "ግዢ ቅርጫት አጽዳ",
    cartEmpty: "ግዢ ቅርጫት ባዶ ነው",
    checkout: "ክፍያ",
    cash: "ጥሬ ገንዘብ",
    card: "ካርድ",
    mobileMoney: "ሞባይል ገንዘብ",
    change: "ቀሪ",
    receipt: "ደረሰኝ",
    printReceipt: "ደረሰኝ አትም",
    paymentSuccess: "ክፍያ ተሳክቷል",
    paymentFailed: "ክፍያ አልተሳካም",
    scanProduct: "ምርት ይቃኙ ወይም ይፈልጉ",
    price: "ዋጋ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key) => {
    // Direct lookup first
    if (translations[language] && translations[language][key] !== undefined) {
      return translations[language][key];
    }
    
    // If not found, try nested lookup (for keys like 'navigation.main')
    const keys = key.split('.');
    let result = translations[language];
    for (const k of keys) {
      if (result && result[k] !== undefined) {
        result = result[k];
      } else {
        // Fallback to English
        let fallback = translations.en;
        for (const fk of keys) {
          if (fallback && fallback[fk] !== undefined) {
            fallback = fallback[fk];
          } else {
            return key;
          }
        }
        return fallback;
      }
    }
    return result || key;
  };

  const toggleLanguage = () => {
    const newLang = language === 'en' ? 'am' : 'en';
    setLanguage(newLang);
    localStorage.setItem('language', newLang);
    window.location.reload();
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
