export const endpoints = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  users: {
    list: '/users',
    detail: (id) => `/users/${id}`,
    create: '/users',
    update: (id) => `/users/${id}`,
    delete: (id) => `/users/${id}`,
    status: (id) => `/users/${id}/status`,
    role: (id) => `/users/${id}/role`,
  },
  inventory: {
    list: '/inventory',
    batches: '/inventory/batches',
    movements: '/inventory/movements',
    expiring: '/inventory/expiring',
    product: (id) => `/inventory/products/${id}`,
    batch: (id) => `/inventory/batches/${id}`,
  },
  sales: {
    list: '/sales',
    create: '/sales',
    detail: (id) => `/sales/${id}`,
    update: (id) => `/sales/${id}`,
    delete: (id) => `/sales/${id}`,
    payment: (id) => `/sales/${id}/payment`,
  },
  reports: {
    inventory: '/reports/inventory',
    sales: '/reports/sales',
    profit: '/reports/profit',
    supplier: '/reports/supplier',
    branch: '/reports/branch',
  },
  dashboard: {
    executive: '/dashboard/executive',
    warehouse: '/dashboard/warehouse',
    branch: '/dashboard/branch',
    accountant: '/dashboard/accountant',
    inventoryManager: '/dashboard/inventory-manager',
    cashier: '/dashboard/cashier',
  },
};

